#!/usr/bin/env bash
# Write a Bash script that transfers a file from our client to a server
# scp Private_key source_file user@ip:destination
if [ $# -lt 3 ]; then
    echo 'Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY'
else
    scp -o StrictHostKeyChecking=no -i "$4" "$1" "$3@$2":~/
fi