#!/usr/bin/env bash
# Configure your Nginx server so that /redirect_me is redirecting to another page.
apt-get -y update
apt-get -y install nginx
ufw allow  'Nginx HTTP' #nginx should be listed on port 80
echo 'Holberton School' > /var/www/html/index.nginx-debian.html
sed -i "46i rewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;" /etc/nginx/sites-available/default 
service nginx restart
