#!/usr/bin/env bash
# This script configures Nginx so that its HTTP response

apt-get -y update
apt-get -y install nginx

service nginx start

config_file="/etc/nginx/sites-available/default"

ufw allow  'Nginx HTTP' #nginx should be listed on port 80
echo 'Holberton School' > /var/www/html/index.nginx-debian.html
sed -i "46i rewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;" /etc/nginx/sites-available/default
echo "Ceci n'est pas une page" > /var/www/html/custom_404.html
sed -i "46i error_page 404 /custom_404.html;" /etc/nginx/sites-available/default

text="server {\n\tadd_header X-Served-By \$hostname;}"
sed -i "/server {/s//$text/" "$config_file"

service nginx restart
