#!/usr/bin/env bash
# Write a Bash script that generates a MySQL dump and creates a compressed archive out of it.
mysqldump --all-databases > backup.sql -uroot -p"$1"
tar -zcvf "$(date '+%d-%m-%Y').tar.gz" backup.sql