#!/usr/bin/env bash
# write a Bash script with the minimum number of commands to automate your fix.
sudo cp /etc/nginx/sites-available/default /etc/nginx/sites-enable/default
sudo service nginx restart
