#!/usr/bin/env bash
# script that gives you information about the
# holbertonschool FILE.
FILE="holbertonschool"

if [ -e "$FILE" ]
then
	echo "holbertonschool file exists"
	if [ -s "$FILE" ]
	then
		echo "holbertonschool file is not empty"
	else
		echo "holbertonschool file is empty"
	fi
	if [ -f "$FILE" ]
	then
		echo "holbertonschool file is a regular FILE"
	fi
else
	echo "holbertonschool file does not exist"
fi