#!/usr/bin/env bash
# script that changes the user as nginx instead of root

# kill another server process 
# also because apache2 is using port 8080
pkill apache2

# change owner and group of ngninx configuraiton file
sudo chown nginx:nginx /etc/nginx/nginx.conf

# change permissions of writting of nginx config file
sudo chmod +w /etc/nginx/nginx.conf

# nginx must be listening on all active IPs on port 8080
sudo sed -i 's/80/8080' /etc/nginx/sites-enabled/default

# restart nginx with the prev config
sudo -u nginx service nginx start